### PR TITLE
EOS-14272:Auth: netty version upgrade from 4.0.31 to 4.1.42

### PR DESCRIPTION
**Pull request by sachitanands**
Upgrade netty version in auth server

Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>

### CODE REVIEW

**Comment by sachitanands** [comment]
PR : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/36/console

**Comment by sachitanands** [comment]
Pre-merge job : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/44

**Review by abhilekh268 — APPROVED** [review]

**Review by bkirunge7 — APPROVED** [review]

**Review by AjinkyaDhumal — APPROVED** [review]
Looks Good.

**Comment by bkirunge7** [comment]
Please run 3 hour s3bench workload with 1mb object size, to rule out any auth server connection and response time issues

**Comment by sachitanands** [comment]
> Please run 3 hour s3bench workload with 1mb object size, to rule out any auth server connection and response time issues

I will check on h/w by replacing authserver jar and will run s3 bench with that setup with 1mb load for 3 hours

**Comment by sachitanands** [comment]
@bkirunge7 
Ran multiple s3bench with different samples and object sizes.. All test went fine without any error ..
below is one such test result,
s3bench command :
` [root@smc45-m09 bin]# /root/go/bin/s3bench -accessKey Fo0yB21VRImZZPfrdrQgyw -accessSecret ntqYZD1xh39gwT5ifoPNVFIOWvWxOBdEFwNtjX8y -bucket testb1 -endpoint https://s3.seagate.com -numClients 128 -numSamples 4096 -objectNamePrefix=s3workload -objectSize 134217728b -skipCleanup --verbose > /root/sachit_128MB_4096Sample_128Clients.log`
Test result : 
    `Operation:                  Write
    Total Requests Count:       4096
    Errors Count:               0
    Total Throughput (MB/s):    1395.589
    Duration Max:               25.068
    Duration Avg:               11.630
    Duration Min:               1.693
    Ttfb Max:                   25.068
    Ttfb Avg:                   11.630
    Ttfb Min:                   1.693
    Duration 90th-ile:          17.461
    Duration 99th-ile:          21.433
    Errors:                     []
    Total Duration (s):         375.675
    Total Transferred (MB):     524288.000
    Ttfb 90th-ile:              17.461
    Ttfb 99th-ile:              21.433

    Operation:                  Read
    Total Requests Count:       4096
    Errors Count:               0
    Total Throughput (MB/s):    1254.053
    Duration Max:               18.715
    Duration Avg:               12.985
    Duration Min:               6.528
    Ttfb Max:                   5.932
    Ttfb Avg:                   3.197
    Ttfb Min:                   0.345
    Duration 90th-ile:          14.936
    Duration 99th-ile:          16.490
    Errors:                     []
    Total Duration (s):         418.075
    Total Transferred (MB):     524288.000
    Ttfb 90th-ile:              4.080
    Ttfb 99th-ile:              4.993`

**Pull request merged**
