### PR TITLE
EOS-16423: S3 Mini-provisioner: Validations in post_install [PR#639 continuation with main]

### PR DESCRIPTION
**Pull request by pratyush-seagate**
### Note to reviewers: This is a clone of [PR#639](https://github.com/Seagate/cortx-s3server/pull/639). After mini-provisioner was deleted, that PR was closed. Hence I have to now create this new PR against the main. Please note that the changes are same and same reviews remain addressed.

commit 99e3cf612061efb0db227faa44fa12ee05100c9b
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Fri Jan 22 03:29:51 2021 -0700

                EOS-16423: S3 Mini-provisioner: Validations in post_install
                Change description:
                Address Amit and Ajinkya's review commentsi to adhere the new format of command args for s3setup
                Files edited/added:
                        modified:   scripts/provisioning/s3_setup
                        modified:   scripts/provisioning/s3setup/s3setup/cortx_s3_setup.py
                        modified:   scripts/provisioning/setup.yaml
                Testing done:
                    Unit tested s3setup changes on VM

    Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

commit 5381df60b08a1e1a3f8d2049f11f7681a8f94a8a
Author: pratyush-seagate <pratyush.k.khan@seagate.com>
Date:   Thu Jan 21 11:42:50 2021 -0700

            EOS-16423: S3 Mini-provisioner: Validations in post_install
            Change description:
                Integrate the new validator APIs from py-utils in s3setup
                Add new s3setup option for validation based on optional external config file for rpms, pip3s and services
                Relevant changes in S3 rpm scripts
                Relevant changes in s3_setup and setup.yaml for post_install
            Files edited/added:
                modified:   installhelper.sh
                modified:   rpms/s3/s3rpm.spec
                modified:   scripts/provisioning/s3_setup
                modified:   scripts/provisioning/s3setup/s3setup/cortx_s3_setup.py
                new file:   scripts/provisioning/s3setup_prereqs.json
                modified:   scripts/provisioning/setup.yaml
            Testing done:
                Unit tested s3setup and s3_setup changes on VM

    Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

### CODE REVIEW

**Comment by pratyush-seagate** [comment]
s3setup -h
usage: s3setup [-h] [--cleanup CLEANUP] [--ldappasswd LDAPPASSWD]
[--validateprerequisites] [--preqs_conf_file PREQS_CONF_FILE]
[--config CONFIG]
[{post_install,cleanup} [{post_install,cleanup} ...]]

Cortx S3 Setup

positional arguments:
{post_install,cleanup}
Perform S3setup mini-provisioner actions

optional arguments:
-h, --help show this help message and exit
--cleanup CLEANUP Cleanup S3 accounts and dependencies. Valid values:
all/accounts/dependencies
--ldappasswd LDAPPASSWD
ldap password, needed for --cleanup
--validateprerequisites
validate prerequisites for mini-provisioner setup
--preqs_conf_file PREQS_CONF_FILE
optional conf file location used with
--validateprerequisites
--config CONFIG config file url, check cortx-py-utils::confstore for
supported formats.

**Comment by pratyush-seagate** [comment]
jenkins started at http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/449/

**Review by amitwac2608 — APPROVED** [review]

**Review by AjinkyaDhumal — APPROVED** [review]

**Comment by pratyush-seagate** [comment]
Jenkins http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/449/ passed.
Since one more minor change was made, started http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/ next.

**Comment by pratyush-seagate** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/452/ passed

**Comment by bkirunge7** [comment]
Codacy validation failing please check

**Comment by pratyush-seagate** [comment]
> 
> 
> Codacy validation failing please check

Thanks, addressed.

**Pull request merged**
