### PR TITLE
[OVA-Bug] EOS-20764:add slapd service dependency in s3authserver.service file

### PR DESCRIPTION
**Pull request by sachitanands**
Handle s3authserver restart dependencies in server file.

Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>

### CODE REVIEW

**Comment by sachitanands** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1149/console

**Review by bkirunge7 — APPROVED** [review]

**Comment by sachitanands** [comment]
Pre-merge : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1176/
Cortx VM Deployment : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/S3Server/665

**Comment by vimalraghwani20** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1182/

**Comment by sachitanands** [comment]
Pre-merge : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1191/
Cortx-Deployment : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/S3Server/674/

**Comment by sachitanands** [comment]
Cortx VM deployment went fine.. Job has passed
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/S3Server/686/ 
Pre-merge job is already passed as mentioned in above comments

**Comment by nileshgovande** [comment]
All jobs including cortx deployment are green. Merging...

**Pull request merged**
