### PR TITLE
[versioning] Merge put/get bucket versioning features to kubernetes branch

### PR DESCRIPTION
**Pull request by indrajitzagade**
# Problem Statement
Merge put/get bucket versioning features to kubernetes branch

# Design
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/762183795/PutBucketVersioning+LLD
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/746946603/GetBucketVersioning+LLD

# Coding
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [x] Unit and System Tests are added
- [x] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s): None

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR: NA
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link: NA
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Comment by indrajitzagade** [comment]
I will build the code in this PR and update the autogenerated files.

**Comment by keithpine** [comment]
Shouldn't this merge also include #1643?

**Comment by indrajitzagade** [comment]
> Shouldn't this merge also include #1643?

@keithpine We discussed this in our DSU. We think that only the QA tested code should be merged into the kubernetes branch. Also not supporting the "Suspended" state is at PI level and we should merge this change before the PI ends, so it can be taken-up for merge in the later PRs before the PI end. Please let us know if you have concerns.

**Comment by indrajitzagade** [comment]
@nileshgovande @t7ko-seagate @knrajnambiar76 Please review this PR.

**Comment by indrajitzagade** [comment]
Pre-merge test job link: http://eos-jenkins.colo.seagate.com/job/S3server/job/S3Server-PreMerge-Test/842/

**Comment by indrajitzagade** [comment]
It was discussed in DSU and decided to keep the features in their respective feature branches. So this PR is not required now, hence closing.
cc @NeeravChoudhari  @keithpine @nileshgovande @knrajnambiar76 @bkirunge7

**Pull request closed without merging**
