### PR TITLE
[EOS-19369] cortx-s3server-test rpm build script does not work with …

### PR DESCRIPTION
**Pull request by SeagateChaDeepak**
-G option changes.
--path optional changes.

Signed-off-by: Deepak Mahale <deepak.mahale@seagate.com>

### CODE REVIEW

**Review by vimalraghwani20 — APPROVED** [review]

**Comment by SeagateChaDeepak** [comment]
MiniProvisioner Job http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/753/

**Review by sachitanands — APPROVED** [review]
looks good ..
please try building s3-test rpm once with -G parameters

**Comment by SeagateChaDeepak** [comment]
> looks good ..
> please try building s3-test rpm once with -G parameters

Done that @sachitanands

**Comment by nileshgovande** [comment]
Mini - provisioner Job - http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/753/

**Pull request merged**
