### PR TITLE
EOS-14459: base64 refactoring

### PR DESCRIPTION
**Pull request by evgeniy-brazhnikov**
Signed-off-by: evgeniy-brazhnikov <evgeniy.brazhnikov@seagate.com>

### CODE REVIEW

**Comment by evgeniy-brazhnikov** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/75/

**Comment by nileshgovande** [comment]
@t7ko-seagate @bkirunge7 - Pls have a look

**Review by t7ko-seagate — CHANGES_REQUESTED** [review]
No faults; just fix those two minor remarks and it can be merged.

**Review by t7ko-seagate — APPROVED** [review]

**Comment by t7ko-seagate** [comment]
FYI: I also wrote a simple test program to measure efficiency, and found that new impl is ~2-3 times faster than current one.

**Review by bkirunge7 — APPROVED** [review]

**Comment by evgeniy-brazhnikov** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/125/

**Pull request merged**
