### PR TITLE
Moved s3-supported-api.md to docs folder

### PR DESCRIPTION
**Pull request by Saumya-Sunder**
Moved s3-supported-api.md to docs folder

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

### CODE REVIEW

**Comment by nileshgovande** [comment]
Do we need to fix any links?

**Comment by Saumya-Sunder** [comment]
We will need to update this link on CORTX parent repo and not here @DPG17 have you linked this doc anywhere?

**Comment by nileshgovande** [comment]
Document movement - no Jenkins needed

**Comment by johnbent** [comment]
All, when you moved this, you forgot to update the links that pointed to it.

**Comment by DPG17** [comment]
> We will need to update this link on CORTX parent repo and not here @DPG17 have you linked this doc anywhere?

@Saumya-Sunder : I've not linked this doc anywhere.

**Pull request merged**
