### PR TITLE
Openldap with selinux disabled

### PR DESCRIPTION
**Pull request by SaumitraK531**
Signed-off-by: Saumitra Kulkarni <saumitra.kulkarni@seagate.com>

### CODE REVIEW

**Comment by SaumitraK531** [comment]
This PR was just for testing OpenLDAP with SELinux policy disabled. 
Closing this PR.

**Comment by mukul-seagate11** [comment]
@all, can this PR be approved & merged as its blocking OVA R2 release

**Review by sachitanands — APPROVED** [review]
Saumitra already tested this .. hence marking it as approved and waiting for pre-merge job to be successful.
once job gets completed we will merge this

**Review by vimalraghwani20 — APPROVED** [review]

**Comment by sachitanands** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1376/consoleFull

**Pull request merged**
