### PR TITLE
EOS-21416: Removed workaround used for iterating all keys using get_all_keys()

### PR DESCRIPTION
**Pull request by vimalraghwani20**
# Change Summary
## Problem Statement/Description
_[EOS-21416](https://jts.seagate.com/browse/EOS-21416):_
_Removed workaround used for iterating all keys using get_all_keys()_

## Solution Overview
- Removed the workaround from get_all_keys()

### CODE REVIEW

**Review by shahidSTX — APPROVED** [review]
LGTM.

**Comment by vimalraghwani20** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/1458/

**Review by sachitanands — APPROVED** [review]
pls check 1Node deployment job link
rest looks good.

**Comment by nileshgovande** [comment]
Mini provisioner: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/1470/
Pre-merge: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1705/
VM deployment: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/S3Server/918/

**Pull request merged**
