### PR TITLE
EOS-14826: [Splunk, ceph] Fix for Ceph S3 failed test cases in ListObject api

### PR DESCRIPTION
**Pull request by DPG17**
Failed TCs are below:
  s3tests.functional.test_s3.test_bucket_list_delimiter_prefix
  s3tests.functional.test_s3.test_bucket_list_delimiter_prefix_underscore

These TCs are now passing. Locally (on my local VM) verified that existing UT and STs are running fine.

Note:
 - QA needs to re-run third party solutions, e.g., veeam backup, and any other solution to make sure there is no regression, before merging to GA branch.

Signed-off-by: ‘Dattaprasad <dattaprasad.govekar@seagate.com>

### CODE REVIEW

**Comment by DPG17** [comment]
Pre merge build http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/57   is in progress...

**Review by amitwac2608 — APPROVED** [review]
Can we have a System Test for this Change ?

**Comment by DPG17** [comment]
Another pre merge build on changes #accedd4bcd36d4b8e3d8d8f52a249747257a1c65 is completed(with success)
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/66/

**Review by knrajnambiar76 — APPROVED** [review]
Comment with scenario say
objects in motr
abc
xyz
boo/1
boo/2
boo/3

whats the output should be when common prefix is boo/ with delimiter / so on will be good

**Pull request merged**
