### PR TITLE
EOS-14296:Auth:bump up junit version 4.12 -> 4.13.1

### PR DESCRIPTION
**Pull request by sachitanands**
Bump up Junit version,
  Old value  : 4.12
  New value : 4.13.1
 
Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>

### CODE REVIEW

**Comment by sachitanands** [comment]
pre-merge job : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server/166

**Review by abhilekh268 — COMMENTED** [review]
test it on fresh vm..once.rest looks good.

**Review by abhilekh268 — APPROVED** [review]

**Review by bkirunge7 — APPROVED** [review]

**Comment by sachitanands** [comment]
Tested these changes on fresh vm and it went fine.

**Comment by sachitanands** [comment]
Ran pre-merge job with latest changes : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server/168

**Pull request merged**
