### PR TITLE
Main candidate 21 may 2021

### PR DESCRIPTION
**Pull request by nileshgovande**
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/Seagate/cortx-s3server/blob/main-candidate-21-May-2021/docs/CORTX-S3 Server Quick Start Guide.md)
[View rendered docs/design/object-protection.md](https://github.com/Seagate/cortx-s3server/blob/main-candidate-21-May-2021/docs/design/object-protection.md)
[View rendered docs/design/pool-version-id.md](https://github.com/Seagate/cortx-s3server/blob/main-candidate-21-May-2021/docs/design/pool-version-id.md)
[View rendered docs/object-protection-testing.md](https://github.com/Seagate/cortx-s3server/blob/main-candidate-21-May-2021/docs/object-protection-testing.md)

### CODE REVIEW

**Review by vimalraghwani20 — APPROVED** [review]

**Comment by nileshgovande** [comment]
http://eos-jenkins.mero.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Splunk/170/
http://eos-jenkins.mero.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Splunk/
http://eos-jenkins.mero.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph/

**Comment by nileshgovande** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1106/

**Comment by nileshgovande** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/S3Server/635/

**Comment by vimalraghwani20** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/1100/console - **Passed**
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1116/console - **In progress**

**Pull request merged**
