### PR TITLE
EOS-18719:Erase haproxy configurations in cleanup phase

### PR DESCRIPTION
**Pull request by pranavPawar07**
Signed-off-by: pranav <pranav.pawar@seagate.com>

### CODE REVIEW

**Comment by gowthamchinna** [comment]
start vm-deployment

**Review by nileshgovande — APPROVED** [review]

**Review by pratyush-seagate — COMMENTED** [review]
IMO, related to handling the haproxy.cfg, this current approach can be improved if we keep a backup while editing "/etc/haproxy/haproxy.cfg" from "./scripts/haproxy/s3haproxyconfig/s3haproxyconfig/s3_haproxy_config.py"

And from this place during cleanup, then we could simply revert the backup file to original.

**Review by sachitanands — APPROVED** [review]
looks good please rebase your changes.

**Review by vimalraghwani20 — APPROVED** [review]

**Comment by nileshgovande** [comment]
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/429/

**Comment by pranavPawar07** [comment]
> http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/429/

**Review by nileshgovande — APPROVED** [review]

**Pull request merged**
