### PR TITLE
[EOS-21010] Changing port to 28071

### PR DESCRIPTION
**Pull request by nileshgovande**
Signed-off-by: Nilesh Govande <nilesh.govande@seagate.com>

-----
[View rendered docs/R2-setup/Haproxy 3 Node load balancing.md](https://github.com/Seagate/cortx-s3server/blob/br/ng/EOS-21010/docs/R2-setup/Haproxy 3 Node load balancing.md)
[View rendered docs/object-protection-testing.md](https://github.com/Seagate/cortx-s3server/blob/br/ng/EOS-21010/docs/object-protection-testing.md)

### CODE REVIEW

**Comment by sachitanands** [comment]
pre-merge : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1340/

**Comment by nileshgovande** [comment]
Premerge pass - http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1344/

**Comment by nileshgovande** [comment]
mini provisioner - http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/1235/

**Review by vimalraghwani20 — APPROVED** [review]

**Comment by nileshgovande** [comment]
Tested mini and cortx provisioning. Merging with HARE.

**Pull request merged**
