### PR TITLE
Remove `pip3` upgrade to avoid conflict

### PR DESCRIPTION
**Pull request by daniarherikurniawan**
Originally, we have to upgrade the pip3 to the latest version. However, that turns out to be a problem down the road when installing cortx-py-utils. Actually, pip3 has been included with the Python installer since versions 3.4 for Python 3.

Regarding how to reproduce the problem:
The cortx-py-utils installation (written here https://github.com/Seagate/cortx-utils/blob/main/py-utils/README.md) will fail when installing`dependent python package`. Specifically, when running this command `sudo pip3 install -r python_requirements.txt`.

The error is:
```sh
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.6/site-packages (from idna-ssl>=1.0->aiohttp==3.6.1->-r python_requirements.txt (line 1)) (2.10)
Using legacy 'setup.py install' for python-crontab, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
Using legacy 'setup.py install' for idna-ssl, since package 'wheel' is not installed.
Installing collected packages: typing-extensions, multidict, yarl, pynacl, numpy, kiwisolver, idna-ssl, elasticsearch, cycler, cryptography, bcrypt, async-timeout, toml, schematics, PyYAML, python-crontab, python-consul, paramiko, networkx, matplotlib, elasticsearch-dsl, confluent-kafka, configparser, aiohttp
    Running setup.py install for idna-ssl ... done
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.1
    Uninstalling cryptography-3.1:
      Successfully uninstalled cryptography-3.1
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
The reason is, the newly upgraded pip3 failed to uninstall `PyYAML` for some reason. However, if we don't upgrade the pip3, it can uninstall `PyYAML` just fine. 
The default pip3 is at version 9.0.3
The upgraded pip3 is at version 21.1.3 

I am not sure why that pip3 version causes this problem, but I've tested and investigated this matter in 6 different nodes (hosted by Chameleon cluster); and avoiding the pip3 upgrade seems to be the easiest solution. 

Let me know if you guys have any questions. I can show you how to reproduce this and give you access to the server.

-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/daniarherikurniawan/cortx-s3server/blob/patch-1/docs/CORTX-S3 Server Quick Start Guide.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by nileshgovande** [comment]
Its becoming specific to the platform (at times we do not have right pip3). @sachinpunadikar pls recommend specific pip3 version

**Comment by daniarherikurniawan** [comment]
Thanks for the reply, @nileshgovande! 
We have to decide what fix should be applied to this problem. Currently, the community can't install s3Server due to this pip3-related bug. 
cc: @bkirunge7 @knrajnambiar76

**Comment by nileshgovande** [comment]
Again @daniarherikurniawan 
latest pip3 was fetched because it had some dependancy with py-utils.(https://github.com/Seagate/cortx-utils) 
I really have no objection if @sachinpunadikar confirms specific pip3 version needed for py-utils

**Comment by johnbent** [comment]
Thanks all.  My only preference is that community can follow the instructions without errors.  Thanks.

**Comment by johnbent** [comment]
@nileshgovande , should we close this, change this, or merge this?

**Comment by nileshgovande** [comment]
For now - we can close this 

@sachinpunadikar - pls chime in.

**Review by sachinpunadikar — APPROVED** [review]
Looks good to me

**Comment by johnbent** [comment]
@bkirunge7 , can you offer your opinion please?

**Comment by bkirunge7** [comment]
I think we should stick to specific pip3 version, I see default pip3 version that gets installed when followed cortx-py-utils installation steps is "pip 9.0.3".  We shouldn't change this later for other components provisioning(s3 server).   @sachinpunadikar

**Comment by bkirunge7** [comment]
@nileshgovande @sachinpunadikar  Lets accept this patch, I dont see need of pip3 latest upgrade, pip 9.0.3 should be fine.

**Pull request merged**
