### PR TITLE
Update CORTX-S3 Server Quick Start Guide.md

### PR DESCRIPTION
**Pull request by mengwanguc**
Add `pip install awscli-plugin-endpoint`
Otherwise will meet `ImportError: No module named awscli_plugin_endpoint` when running ` aws configure set s3.endpoint_url http://s3.seagate.com`

Signed-off-by: Meng Wang <mengwanguc@gmail.com>

-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/mengwanguc/cortx-s3server/blob/patch-3/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by nileshgovande** [comment]
Thanks, @mengwanguc  for your comment
This step is already included in 1.4.5 section so you should not see this error.

**Comment by mengwanguc** [comment]
Hi @nileshgovande , thanks for you quick response

I did follow that `pip3 install`. However, I still saw this error. Somehow my `aws configure` is using python 2.7 by default:

```
[root@s3 cc]# aws configure set s3.endpoint_url https://s3.seagate.com
Traceback (most recent call last):
  File "/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 79, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/usr/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/lib/python2.7/site-packages/awscli/plugin.py", line 58, in _import_plugins
    plugins.append(__import__(path))
ImportError: No module named awscli_plugin_endpoint
```

I double checked it. I did `pip uninstall awscli_plugin_endpoint` and `pip3 install awscli_plugin_endpoint` to uninstall the pip version but keep the pip3 version. In this case I can still see the error above.

**Comment by nileshgovande** [comment]
Let's merge it then 
Anyway - it does not break anything if we have both packages in there.

**Pull request merged**
