### PR TITLE
Moved docs from CORTX Parent to S3 repo

### PR DESCRIPTION
**Pull request by Saumya-Sunder**
Moved docs from CORTX Parent to S3 repo

Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

### CODE REVIEW

**Comment by nileshgovande** [comment]
Images don't seem to be visible

**Comment by Saumya-Sunder** [comment]
Fixed @nileshgovande

**Comment by nileshgovande** [comment]
Certain images seem to be out of date in this PR - example 'cassendra' as KV store part. Tagging @shalakadharap and @DPG17  - Pls review and provide inputs

**Comment by nileshgovande** [comment]
Also - make sure that all the 'images' are in one common 'images' directory and not scattered around in the repo

**Comment by Saumya-Sunder** [comment]
Yes @nileshgovande , I placed the images in the S3 Images folder https://github.com/Seagate/cortx-s3server/tree/35ba0ef51f3ab0dfc055c6c78887fcdbf4fd82c3/images

**Comment by amitwac2608** [comment]
> 
> 
> Certain images seem to be out of date in this PR - example 'cassendra' as KV store part. Tagging @shalakadharap and @DPG17 - Pls review and provide inputs

Yes, Images in the document are old. We are using 'Mero', 'Clovis' terms in the document.

Should we add a Note in the Doc, like read 'Mero' as 'Motr' for readers ?

**Comment by Saumya-Sunder** [comment]
Hey @amitwac2608 we will have to change the names. I will do that on the .md version, for images, I confirmed with John that we need to create them using opensource editors like PlantUrl or Graphwiz and provide the code so that the community can contribute towards images in future. So let me know what do I need to update in images and I will do the needful.

**Comment by shanbhagsv1** [comment]
@Saumya-Sunder Please update the images with following fixes
mero    ->   motr
clovis   ->   motr(@nileshgovande  Please confirm this)
eos      ->   cortx

**Comment by Saumya-Sunder** [comment]
Please approve the ticket as I need to add the updated PlantUML diagrams as discussed on mail @nileshgovande

**Comment by shanbhagsv1** [comment]
As discussed with @Saumya-Sunder  diagrams will be updated in a different PR. Rest changes look good hence approving.

**Review by shanbhagsv1 — APPROVED** [review]

**Review by amitwac2608 — APPROVED** [review]

**Comment by nileshgovande** [comment]
Documentation changes only - merged

**Pull request merged**
